<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.18.4" />
    <PackageReference Include="FluentAssertions" Version="6.8.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
    <PackageReference Include="Tomlyn" Version="0.16.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Primo.MIA.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="PresentationFramework" />
    <Reference Include="PresentationCore" />
    <Reference Include="WindowsBase" />
    <Reference Include="LTools.Common">
      <HintPath>C:\Program Files\Primo\Primo Studio Community x64\LTools.Common.dll</HintPath>
    </Reference>
    <Reference Include="LTools.Dto">
      <HintPath>C:\Program Files\Primo\Primo Studio Community x64\LTools.Dto.dll</HintPath>
    </Reference>
    <Reference Include="LTools.Enums">
      <HintPath>C:\Program Files\Primo\Primo Studio Community x64\LTools.Enums.dll</HintPath>
    </Reference>
    <Reference Include="LTools.Scripting">
      <HintPath>C:\Program Files\Primo\Primo Studio Community x64\LTools.Scripting.dll</HintPath>
    </Reference>
    <Reference Include="LTools.SDK">
      <HintPath>C:\Program Files\Primo\Primo Studio Community x64\LTools.SDK.dll</HintPath>
    </Reference>
    <Reference Include="LTools.Workflow">
      <HintPath>C:\Program Files\Primo\Primo Studio Community x64\LTools.Workflow.dll</HintPath>
    </Reference>
    <Reference Include="Primo.Orchestrator.Client.Common">
      <HintPath>C:\Program Files\Primo\Primo Studio Community x64\Primo.Orchestrator.Client.Common.dll</HintPath>
    </Reference>
    <Reference Include="Primo.Orchestrator.Client.FW">
      <HintPath>C:\Program Files\Primo\Primo Studio Community x64\Primo.Orchestrator.Client.FW.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="calendar\**\*">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
